# 第 1 节　使用 Python 进行描述统计：单变量

## 第 3 章　使用 Pyhton 进行数据分析｜用 Python 动手学统计学

### 1. 统计分析与 scipy

In [1]:
# 用于数值计算的库
import numpy as np
import scipy as sp

# 设置浮点数打印精度
%precision 3

'%.3f'

### 2. 单变量数据的操作

In [2]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

### 3. 实现：总和与样本容量

In [3]:
# 总和
sp.sum(fish_data)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  


40

In [4]:
# 参考
np.sum(fish_data)

40

In [5]:
# 参考
fish_data.sum()

40

In [6]:
# 参考
sum(fish_data)

40

In [7]:
# 样本容量
len(fish_data)

10

### 4. 实现：均值（期望值）

In [8]:
# 计算均值
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  This is separate from the ipykernel package so we can avoid doing imports until


4.0

In [9]:
# 计算均值的函数
sp.mean(fish_data)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  


4.0

### 5. 实现：样本方差

In [10]:
# 样本方差
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  


1.2

In [11]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [12]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [13]:
(fish_data - mu) ** 2

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [14]:
sp.sum((fish_data - mu) ** 2)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  """Entry point for launching an IPython kernel.


12.0

In [15]:
# 计算样本方差的函数
sp.var(fish_data, ddof = 0)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  


1.2

### 6. 实现：无偏方差

In [16]:
# 无偏方差
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  


1.3333333333333333

In [17]:
# 无偏方差
sp.var(fish_data, ddof = 1)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  


1.3333333333333333

### 7. 实现：标准差

In [18]:
# 标准差
sigma = sp.sqrt(sigma_2)
sigma

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  


1.1547005383792515

In [19]:
# 计算标准差的函数
sp.std(fish_data, ddof = 1)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  


1.1547005383792515

### 8. 补充：标准化

In [20]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [21]:
sp.mean(fish_data - mu)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  """Entry point for launching an IPython kernel.


0.0

In [22]:
fish_data / sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [23]:
sp.std(fish_data / sigma, ddof = 1)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  """Entry point for launching an IPython kernel.


1.0

In [24]:
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [25]:
sp.mean(standard)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  """Entry point for launching an IPython kernel.


2.2204460492503132e-17

In [26]:
sp.std(standard, ddof = 1)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  """Entry point for launching an IPython kernel.


1.0

### 9. 补充：其他统计量

In [27]:
# 最大值
sp.amax(fish_data)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  


6

In [28]:
# 最小值
sp.amin(fish_data)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.amin is deprecated and will be removed in SciPy 2.0.0, use numpy.amin instead
  


2

In [29]:
# 中位数
sp.median(fish_data)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  


4.0

In [30]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [31]:
sp.mean(fish_data_2)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  """Entry point for launching an IPython kernel.


13.4

In [32]:
sp.median(fish_data_2)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  """Entry point for launching an IPython kernel.


4.0

### 10. 实现：scipy.stats 与四分位数

In [33]:
from scipy import stats

In [34]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.0

In [35]:
stats.scoreatpercentile(fish_data_3, 75)

7.0